project_id = "nimuqswtprxgoqchrwni"

[functions.generate-financial-plan]
verify_jwt = false

[functions.extract-actions]
verify_jwt = false

[functions.parse-w2]
verify_jwt = false

[functions.plaid-create-link-token]
verify_jwt = false

[functions.plaid-exchange-token]
verify_jwt = false

[functions.plaid-get-accounts]
verify_jwt = false
